# Practice Questions for numpy
Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

Find common elements between A and B. [Hint : Intersection of two sets]

Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [28]:
import numpy as np
A=np.array([1,3,5,7,9,10])
B=np.array([2,3,5,7,10,12])

print(np.vstack([A,B]))

[[ 1  3  5  7  9 10]
 [ 2  3  5  7 10 12]]


In [17]:
print(np.hstack([A,B]))

[ 1  3  5  7  9 10  2  3  5  7 10 12]


In [27]:
C=np.intersect1d(A,B)
C

array([ 3,  5,  7, 10])

In [37]:
SpecificRange=np.where((A>=5)&(A<=10))
result=A[SpecificRange]
result

array([ 5,  7,  9, 10])

In [41]:
## Optional Practice Question

#Find the mean of a numeric column grouped by a categorical column in a 2D numpy array

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


numeric_column = iris[:, 1].astype('float')  # sepalwidth
grouping_column = iris[:, 4]  # species

output = []
numeric_column>1.5 & grouping_column< 5

output

TypeError: unsupported operand type(s) for &: 'float' and 'bytes'

Practice Questions for Pandas
From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

Replace missing values in Min.Price and Max.Price columns with their respective mean.

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
How to get the rows of a dataframe with row sum > 100?
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))